### ISSUE TITLE
reload onFlip

### ISSUE THREAD

**Issue by westonkelliher** [westonkelliher/KeyWords#22]
this should be a quick dirty way to work around the resize bug on flip

**Comment by safwaan-menk** [comment]
Fixed with commit [1344eeb](https://github.com/RecBox-Games/KeyWords/commit/1344eeb8c6c4168de12570072b7d49c933dfb49c)

**Comment by safwaan-menk** [comment]
Closing with commit [1344eeb](https://github.com/RecBox-Games/KeyWords/commit/1344eeb8c6c4168de12570072b7d49c933dfb49c)
