### ISSUE TITLE
attempt to subtract with overflow -> enemy had 1 life, used 2 swords -> src/graphical.rs:421:37 (only happens when using swords

### ISSUE THREAD

**Issue by FlavorlessQuark** [westonkelliher/KeyWords#4]

**Comment by westonkelliher** [comment]
@FlavorlessQuark Wasn't this fixed?

**Comment by safwaan-menk** [comment]
Fixed with commit [0f73f64](https://github.com/RecBox-Games/KeyWords/commit/0f73f645aadee6b0e4cd04bca75532d12dc6a604)

**Comment by safwaan-menk** [comment]
Fixed with commit [0f73f64](https://github.com/RecBox-Games/KeyWords/commit/0f73f645aadee6b0e4cd04bca75532d12dc6a604)
